### ISSUE TITLE
Finalizing pattern docs - Completed

### ISSUE THREAD

**Issue by CedricRobitaille** [CedricRobitaille/ecommerce-pattern-library#24]
@Thomasjbradley

I have created the README.md and have adjusted all remaining config.yml files.

There is one issue however. For the /cards/config.yml, for the product-card and product-card-home, examples are not updating on the pattern library. Would know know why that would be?

**Comment by thomasjbradley** [comment]
Any errors in your Terminal?

**Comment by CedricRobitaille** [comment]
@thomasjbradley 

Nope, it's error free. This has been persisting since I made the cards get data from the .md files.

**Comment by thomasjbradley** [comment]
You need to use the data source style field, like this:

```yml
- name: "data"
  type: "object"
  data:
    source: "site.data.products[1]"
    type: "Product"
```
