### ISSUE TITLE
Preparing Product Data completed + questions.

### ISSUE THREAD

**Issue by CedricRobitaille** [CedricRobitaille/ecommerce-pattern-library#4]
Completion seen on the product page.
Note: Footer content will fill in as more _products are available.

Question:
1. How do I vertically centre the content in the rightmost textbox while in content-distribute.
2. I want the extra content to be shown as 'related content', how do I specify to seek out related content?

@thomasjbradley

**Comment by thomasjbradley** [comment]
*Vertical centring—*

I’d probably target `.card-color` and add some Flexbox:

```css
.card-color {
  display: flex;
  flex-direction: row;
  justify-content: center;
}
```
